### ISSUE TITLE
Partial cost-coverage data problems

### ISSUE THREAD

**Issue by Rowanmh** [optimamodel/Optima#792]
Many programs have only partial cost-coverage data, e.g. one but not the other for a given year.  Attempting to add partial data generates an error on every page refresh, although it does save the partial data correctly.  Tested on Zambia, ART program, Define cost and outcome functions page.

Adding coverage data without cost data gives:
```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 67, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project_progsets.py", line 451, in get
    plot = program.plotcoverage(t=t, parset=parset, plotoptions=plotoptions)
  File "/opt/optima/optima/programs.py", line 882, in plotcoverage
    if costdata: xupperlim = 1.5*max(costdata)
TypeError: can't multiply sequence by non-int of type 'float'
```

Adding cost data without coverage data gives:
```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 67, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project_progsets.py", line 451, in get
    plot = program.plotcoverage(t=t, parset=parset, plotoptions=plotoptions)
  File "/opt/optima/optima/programs.py", line 941, in plotcoverage
    color='#666666')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 3675, in scatter
    self.add_collection(collection)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1459, in add_collection
    self.update_datalim(collection.get_datalim(self.transData))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py", line 189, in get_datalim
    offsets = np.asanyarray(offsets, np.float_)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 525, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not convert string to float: 
```

In both cases this will prevent the graph from being drawn.

**Comment by Rowanmh** [comment]
Note that this could probably be fixed by simply ignoring any entries with only partial cost-coverage data instead of trying to create a data point to put into the graph.

The far more difficult stretch goal here could be to add uncertainty bars instead of points based on other nearby data points assuming that e.g. coverage for 2007 is known but cost could be between known values for 2006 and 2010.

**Comment by boscoh** [comment]
Thanks @Rowanmh. This is really useful error reporting. It's going to be really helpful for debugging!

**Comment by robynstuart** [comment]
@boscoh this looks like a BE issue.... I can fix it by preventing the code from trying to plot incomplete (cost,cov) pairs.

**Comment by robynstuart** [comment]
@boscoh i've checked this out & the back-end is working fine on branch `fix/conversions-not-handling-ints`. The converted projects now store all cost& coverage data. I've confirmed that this works fine in the back-end, and i can plot the cost functions there without a problem. However, when i upload to the FE, the partial data years still don't appear. Can you please look at the asap? It should be possible to enter partial data in the table pasted here, i.e. you should be able to leave either the cost or the coverage entry blank.
![screen shot 2016-05-18 at 8 54 58 pm](https://cloud.githubusercontent.com/assets/9333040/15371336/37aa73ce-1d3b-11e6-972f-c3c3d3529346.png)
